### ISSUE TITLE
Has splits.py been released?

### ISSUE THREAD

**Issue by leoyao-lzy** [huiyegit/UAV3D#1]
hi Ye, I want to train BEVFormer with the mini dataset. Has the splits.py for splitting the scene been released?

**Comment by huiyegit** [comment]
The splits.py file can be found here: https://github.com/huiyegit/UAV3D/blob/main/perception/bevfusion/projects/splits.py
For BEVFormer, you may need to preprocess the dataset.  You can refer to the code  here : https://github.com/huiyegit/UAV3D/blob/main/perception/bevfusion/tools/data_converter/uav_converter_mini.py

**Comment by leoyao-lzy** [comment]
thanks Ye. And one more thing, did you provide 'LIDAR_TOP' information in mini dataset?

**Comment by huiyegit** [comment]
The drone platform does not have the LiDAR sensor; however, the processed format of the dataset (i.e., uav3d_infos_train.pkl) includes pseudo-LiDAR coordinates similar to those in the NuScenes dataset.
