### ISSUE TITLE
Pretrained models for training

### ISSUE THREAD

**Issue by hanzi326** [huiyegit/UAV3D#2]
Thanks for your excellent works!
According to the train_eval.md file, the swint-nuimages-pretrained.pth is needed in the training process of collaborative object detection. How can I find and download the .pth models?
Thank you!

**Comment by huiyegit** [comment]
The pretained model is from the BEVFusion Git repo:  https://github.com/mit-han-lab/bevfusion.
You can also find it here :  https://drive.google.com/file/d/1n0x835VRSoyFVJIW-NHRnJuGtvQy5zXY/view?usp=share_link

**Comment by hanzi326** [comment]
> The pretained model is from the BEVFusion Git repo: https://github.com/mit-han-lab/bevfusion. You can also find it here : https://drive.google.com/file/d/1n0x835VRSoyFVJIW-NHRnJuGtvQy5zXY/view?usp=share_link

Thank you very much for your patient reply. I may bother you again if I run into other problems in reproducing the code.

**Comment by icefrogplus** [comment]
what's wrong about it

```txt
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 85, in main
    if model.com_type == "DiscoNet":
  File "/home1/xjh/conda/envs/uavbevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BEVFusion' object has no attribute 'com_type'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
