### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by Zheng-haowen** [huiyegit/UAV3D#3]
Thanks for the great work！
I seem to have some problems with visualization. I am executing the code in `perception/bevfusion/tools/visualize.py` and the visualization of gt does not seem to match the original image.
![image](https://github.com/user-attachments/assets/fee9d656-b6d1-4019-92f1-bde052243877)

**Comment by huiyegit** [comment]
Please try this source code:  https://github.com/huiyegit/UAV3D/blob/main/visualization/visualization_uav.py

**Comment by icefrogplus** [comment]
bro realize it?
