### ISSUE TITLE
About transformation

### ISSUE THREAD

**Issue by uestchjw** [huiyegit/UAV3D#4]
Thanks for your contributing work.
  In your paper, the ego coordinate system and global coordinate system share the same origin and axis direction, as "In UAV3D, the Ego-UAV coordinate system is aligned with the global coordinate system in Unreal Engine 4, and they share the same origin and orientation of the X, Y, and Z axes. ". However, in uav3d_infos_val.pkl, each frame has a "ego2global_translation" attribute(not zero), which seems to be different from the expression in the paper.
  Another question is: Is the transformation matrix in "calibrated_sensor.json" the final version? I mean has it already taken into account the chiral transformation? And is it a transformation to the ego coordinate system or the global coordinate system?
  Thanks for your reply.

**Comment by huiyegit** [comment]
The  ego coordinate system and global coordinate system  share the orientation of the X, Y, and Z axes, but the origins are different. The description in the paper is not accurate.
The transformation matrix in the  "calibrated_sensor.json" should be in the the global coordinate system.

**Comment by uestchjw** [comment]
Very thanks. 
If I want to convert a point in camera coordinate to global coordinate system, should I directly use the rotation and translation in "calibrated_sensor.json" or do I need an additional chiral transformation matrix? This really confuses me.
![aa](https://github.com/user-attachments/assets/3e8b8143-7cff-4ce2-a404-855a08befd16)

**Comment by huiyegit** [comment]
The paper presents the transformation process from World Coordinate System to Pixel Coordinates, which can be used for visualization. The transformation matrix in "calibrated_sensor.json" represents the  transformation from the camera coordinate to global coordinate system. You can refer to the source code of this transformation: https://github.com/huiyegit/UAV3D/blob/main/perception/bevfusion/tools/data_converter/uav_converter.py

**Comment by uestchjw** [comment]
Thanks for your reply, I have resolved my issue.
